import { QuizQuestion } from "./types";

export const quizQuestions: QuizQuestion[] = [
  {
    id: "jobTitle",
    title: "What's your job title?",
    subtitle: "Pick the closest match to your current role",
    type: "search",
    options: [
      { value: "software-engineer", label: "Software Engineer", riskWeight: 35 },
      { value: "data-analyst", label: "Data Analyst", riskWeight: 55 },
      { value: "product-manager", label: "Product Manager", riskWeight: 25 },
      { value: "designer", label: "UX/UI Designer", riskWeight: 30 },
      { value: "marketing-manager", label: "Marketing Manager", riskWeight: 40 },
      { value: "copywriter", label: "Copywriter / Content Writer", riskWeight: 65 },
      { value: "accountant", label: "Accountant", riskWeight: 70 },
      { value: "financial-analyst", label: "Financial Analyst", riskWeight: 55 },
      { value: "hr-manager", label: "HR Manager", riskWeight: 35 },
      { value: "recruiter", label: "Recruiter", riskWeight: 50 },
      { value: "sales-rep", label: "Sales Representative", riskWeight: 30 },
      { value: "customer-support", label: "Customer Support", riskWeight: 75 },
      { value: "project-manager", label: "Project Manager", riskWeight: 30 },
      { value: "admin-assistant", label: "Administrative Assistant", riskWeight: 80 },
      { value: "paralegal", label: "Paralegal", riskWeight: 65 },
      { value: "lawyer", label: "Lawyer", riskWeight: 25 },
      { value: "teacher", label: "Teacher / Educator", riskWeight: 20 },
      { value: "nurse", label: "Nurse", riskWeight: 10 },
      { value: "doctor", label: "Doctor / Physician", riskWeight: 10 },
      { value: "pharmacist", label: "Pharmacist", riskWeight: 40 },
      { value: "journalist", label: "Journalist", riskWeight: 55 },
      { value: "graphic-designer", label: "Graphic Designer", riskWeight: 50 },
      { value: "video-editor", label: "Video Editor", riskWeight: 40 },
      { value: "photographer", label: "Photographer", riskWeight: 25 },
      { value: "real-estate-agent", label: "Real Estate Agent", riskWeight: 30 },
      { value: "supply-chain", label: "Supply Chain / Logistics", riskWeight: 50 },
      { value: "warehouse-worker", label: "Warehouse Worker", riskWeight: 60 },
      { value: "truck-driver", label: "Truck Driver", riskWeight: 55 },
      { value: "retail-worker", label: "Retail Worker", riskWeight: 65 },
      { value: "chef", label: "Chef / Cook", riskWeight: 15 },
      { value: "electrician", label: "Electrician", riskWeight: 10 },
      { value: "plumber", label: "Plumber", riskWeight: 8 },
      { value: "mechanic", label: "Mechanic", riskWeight: 12 },
      { value: "consultant", label: "Consultant", riskWeight: 30 },
      { value: "researcher", label: "Researcher / Scientist", riskWeight: 20 },
      { value: "devops-engineer", label: "DevOps Engineer", riskWeight: 30 },
      { value: "qa-tester", label: "QA / Test Engineer", riskWeight: 55 },
      { value: "business-analyst", label: "Business Analyst", riskWeight: 45 },
      { value: "executive", label: "Executive / C-Suite", riskWeight: 15 },
      { value: "other", label: "Other", riskWeight: 40 },
    ],
  },
  {
    id: "industry",
    title: "What industry do you work in?",
    subtitle: "This helps us assess sector-specific AI adoption trends",
    type: "single",
    options: [
      { value: "tech", label: "Technology", riskWeight: 40 },
      { value: "finance", label: "Finance & Banking", riskWeight: 55 },
      { value: "healthcare", label: "Healthcare", riskWeight: 20 },
      { value: "education", label: "Education", riskWeight: 25 },
      { value: "retail", label: "Retail & E-commerce", riskWeight: 55 },
      { value: "manufacturing", label: "Manufacturing", riskWeight: 50 },
      { value: "media", label: "Media & Entertainment", riskWeight: 50 },
      { value: "legal", label: "Legal", riskWeight: 40 },
      { value: "real-estate", label: "Real Estate", riskWeight: 30 },
      { value: "government", label: "Government", riskWeight: 25 },
      { value: "marketing", label: "Marketing & Advertising", riskWeight: 55 },
      { value: "consulting", label: "Consulting", riskWeight: 35 },
      { value: "transportation", label: "Transportation & Logistics", riskWeight: 50 },
      { value: "energy", label: "Energy & Utilities", riskWeight: 30 },
      { value: "hospitality", label: "Hospitality & Food Service", riskWeight: 35 },
      { value: "construction", label: "Construction", riskWeight: 15 },
      { value: "nonprofit", label: "Nonprofit", riskWeight: 25 },
      { value: "other", label: "Other", riskWeight: 35 },
    ],
  },
  {
    id: "experience",
    title: "How many years of experience?",
    subtitle: "Your experience level affects how adaptable your role is",
    type: "single",
    options: [
      { value: "0-2", label: "0–2 years", riskWeight: 60 },
      { value: "3-5", label: "3–5 years", riskWeight: 45 },
      { value: "6-10", label: "6–10 years", riskWeight: 30 },
      { value: "10+", label: "10+ years", riskWeight: 20 },
    ],
  },
  {
    id: "skills",
    title: "What are your strongest skills?",
    subtitle: "Pick up to 5 skills that define your work",
    type: "multi",
    maxSelections: 5,
    options: [
      { value: "data-entry", label: "Data Entry", riskWeight: 90 },
      { value: "spreadsheets", label: "Spreadsheets & Excel", riskWeight: 60 },
      { value: "writing", label: "Writing & Editing", riskWeight: 55 },
      { value: "coding", label: "Programming / Coding", riskWeight: 30 },
      { value: "design", label: "Visual Design", riskWeight: 35 },
      { value: "research", label: "Research & Analysis", riskWeight: 40 },
      { value: "project-mgmt", label: "Project Management", riskWeight: 25 },
      { value: "leadership", label: "Leadership & Strategy", riskWeight: 15 },
      { value: "customer-service", label: "Customer Service", riskWeight: 65 },
      { value: "sales", label: "Sales & Negotiation", riskWeight: 25 },
      { value: "marketing", label: "Digital Marketing", riskWeight: 50 },
      { value: "accounting", label: "Bookkeeping & Accounting", riskWeight: 70 },
      { value: "legal-work", label: "Legal Research & Drafting", riskWeight: 55 },
      { value: "teaching", label: "Teaching & Training", riskWeight: 20 },
      { value: "creative", label: "Creative Problem Solving", riskWeight: 15 },
      { value: "communication", label: "Communication & Presenting", riskWeight: 15 },
      { value: "manual-work", label: "Physical / Manual Work", riskWeight: 10 },
      { value: "healthcare-skills", label: "Patient Care", riskWeight: 10 },
      { value: "translation", label: "Translation", riskWeight: 70 },
      { value: "scheduling", label: "Scheduling & Coordination", riskWeight: 75 },
    ],
  },
  {
    id: "tasks",
    title: "What fills most of your day?",
    subtitle: "Pick the 3 tasks you spend the most time on",
    type: "multi",
    maxSelections: 3,
    options: [
      { value: "emails", label: "Emails & messages", riskWeight: 70 },
      { value: "reports", label: "Writing reports & docs", riskWeight: 60 },
      { value: "data-processing", label: "Processing data", riskWeight: 80 },
      { value: "meetings", label: "Meetings & calls", riskWeight: 20 },
      { value: "planning", label: "Planning & strategy", riskWeight: 15 },
      { value: "creative-work", label: "Creative work", riskWeight: 25 },
      { value: "coding-tasks", label: "Writing code", riskWeight: 35 },
      { value: "customer-facing", label: "Talking to customers", riskWeight: 30 },
      { value: "teaching-training", label: "Teaching / training others", riskWeight: 15 },
      { value: "physical-tasks", label: "Physical / hands-on work", riskWeight: 10 },
      { value: "filing", label: "Filing & organizing", riskWeight: 85 },
      { value: "reviewing", label: "Reviewing & approving", riskWeight: 40 },
      { value: "scheduling-tasks", label: "Scheduling & coordination", riskWeight: 75 },
      { value: "research-tasks", label: "Research & analysis", riskWeight: 45 },
    ],
  },
];
